In [15]:
import numpy as np
import pandas as pd

In [9]:
from datascience import *
#import Table

In [10]:
help(Table)

Help on class Table in module datascience.tables:

class Table(collections.abc.MutableMapping)
 |  A sequence of string-labeled columns.
 |
 |  Method resolution order:
 |      Table
 |      collections.abc.MutableMapping
 |      collections.abc.Mapping
 |      collections.abc.Sized
 |      collections.abc.Iterable
 |      collections.abc.Container
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __delitem__(self, index_or_label)
 |
 |  __getattr__(self, attr)
 |      Return a method that applies to all columns or a table of attributes. [Deprecated]
 |
 |      E.g., t.sum() on a Table will return a table with the sum of each column.
 |
 |  __getitem__(self, index_or_label)
 |
 |  __init__(self, labels=None, formatter=<datascience.formats.Formatter object at 0x1145810b8>)
 |      Create an empty table with column labels.
 |
 |      >>> tiles = Table(make_array('letter', 'count', 'points'))
 |      >>> tiles
 |      letter | count | points
 |
 |      Args:
 |          ``labels`` (list of strings): The column labels.
 |
 |          ``formatter`` (Formatter): An instance of :class:`Formatter` that
 |              formats the columns' values.
 |
 |  __iter__(self)
 |
 |  __len__(self)
 |
 |  __repr__ = __str__(self)
 |
 |  __setitem__(self, index_or_label, values)
 |
 |  __str__(self)
 |      Return str(self).
 |
 |  append(self, row_or_table)
 |      Append a row or all rows of a table. An appended table must have all
 |      columns of self.
 |
 |  append_column(self, label, values, formatter=None)
 |      Appends a column to the table or replaces a column.
 |
 |      ``__setitem__`` is aliased to this method:
 |          ``table.append_column('new_col', make_array(1, 2, 3))`` is equivalent to
 |          ``table['new_col'] = make_array(1, 2, 3)``.
 |
 |      Args:
 |          ``label`` (str): The label of the new column.
 |
 |          ``values`` (single value or list/array): If a single value, every
 |              value in the new column is ``values``.
 |
 |              If a list or array, the new column contains the values in
 |              ``values``, which must be the same length as the table.
 |          ``formatter`` (single formatter): Adds a formatter to the column being
 |              appended. No formatter added by default.
 |
 |      Returns:
 |          Original table with new or replaced column
 |
 |      Raises:
 |          ``ValueError``: If
 |              - ``label`` is not a string.
 |              - ``values`` is a list/array and does not have the same length
 |                as the number of rows in the table.
 |
 |      >>> table = Table().with_columns(
 |      ...     'letter', make_array('a', 'b', 'c', 'z'),
 |      ...     'count',  make_array(9, 3, 3, 1),
 |      ...     'points', make_array(1, 2, 2, 10))
 |      >>> table
 |      letter | count | points
 |      a      | 9     | 1
 |      b      | 3     | 2
 |      c      | 3     | 2
 |      z      | 1     | 10
 |      >>> table.append_column('new_col1', make_array(10, 20, 30, 40))
 |      letter | count | points | new_col1
 |      a      | 9     | 1      | 10
 |      b      | 3     | 2      | 20
 |      c      | 3     | 2      | 30
 |      z      | 1     | 10     | 40
 |      >>> table.append_column('new_col2', 'hello')
 |      letter | count | points | new_col1 | new_col2
 |      a      | 9     | 1      | 10       | hello
 |      b      | 3     | 2      | 20       | hello
 |      c      | 3     | 2      | 30       | hello
 |      z      | 1     | 10     | 40       | hello
 |      >>> table.append_column(123, make_array(1, 2, 3, 4))
 |      Traceback (most recent call last):
 |          ...
 |      ValueError: The column label must be a string, but a int was given
 |      >>> table.append_column('bad_col', [1, 2])
 |      Traceback (most recent call last):
 |          ...
 |      ValueError: Column length mismatch. New column does not have the same number of rows as table.
 |
 |  apply(self, fn, *column_or_columns)
 |      Apply ``fn`` to each element or elements of ``column_or_columns``.
 |      If no ``column_or_columns`` provided, `fn`` is applied to each row.
 |
 |      Args:
 |          ``fn`` (function) -- The function to apply to each element
 |              of ``column_or_columns``.
 |          ``column_or_columns`` -- Columns containing the arguments to ``fn``
 |              as either column labels (``str``) or column indices (``int``).
 |              The number of columns must match the number of arguments
 |              that ``fn`` expects.
 |
 |      Raises:
 |          ``ValueError`` -- if  ``column_label`` is not an existing
 |              column in the table.
 |          ``TypeError`` -- if insufficent number of ``column_label`` passed
 |              to ``fn``.
 |
 |      Returns:
 |          An array consisting of results of applying ``fn`` to elements
 |          specified by ``column_label`` in each row.
 |
 |      >>> t = Table().with_columns(
 |      ...     'letter', make_array('a', 'b', 'c', 'z'),
 |      ...     'count',  make_array(9, 3, 3, 1),
 |      ...     'points', make_array(1, 2, 2, 10))
 |      >>> t
 |      letter | count | points
 |      a      | 9     | 1
 |      b      | 3     | 2
 |      c      | 3     | 2
 |      z      | 1     | 10
 |      >>> t.apply(lambda x: x - 1, 'points')
 |      array([0, 1, 1, 9])
 |      >>> t.apply(lambda x, y: x * y, 'count', 'points')
 |      array([ 9,  6,  6, 10])
 |      >>> t.apply(lambda x: x - 1, 'count', 'points')
 |      Traceback (most recent call last):
 |          ...
 |      TypeError: <lambda>() takes 1 positional argument but 2 were given
 |      >>> t.apply(lambda x: x - 1, 'counts')
 |      Traceback (most recent call last):
 |          ...
 |      ValueError: The column "counts" is not in the table. The table contains these columns: letter, count, points
 |
 |      Whole rows are passed to the function if no columns are specified.
 |
 |      >>> t.apply(lambda row: row[1] * 2)
 |      array([18,  6,  6,  2])
 |
 |  as_html(self, max_rows=0)
 |      Format table as HTML.
 |
 |  as_text(self, max_rows=0, sep=' | ')
 |      Format table as text.
 |
 |  bar(self, column_for_categories=None, select=None, overlay=True, width=6, height=4, **vargs)
 |      Plot bar charts for the table.
 |
 |      Each plot is labeled using the values in `column_for_categories` and
 |      one plot is produced for every other column (or for the columns
 |      designated by `select`).
 |
 |      Every selected column except `column_for_categories` must be numerical.
 |
 |      Args:
 |          column_for_categories (str): A column containing x-axis categories
 |
 |      Kwargs:
 |          overlay (bool): create a chart with one color per data column;
 |              if False, each will be displayed separately.
 |
 |          vargs: Additional arguments that get passed into `plt.bar`.
 |              See http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.bar
 |              for additional arguments that can be passed into vargs.
 |
 |  barh(self, column_for_categories=None, select=None, overlay=True, width=6, **vargs)
 |      Plot horizontal bar charts for the table.
 |
 |      Args:
 |          ``column_for_categories`` (``str``): A column containing y-axis categories
 |              used to create buckets for bar chart.
 |
 |      Kwargs:
 |          overlay (bool): create a chart with one color per data column;
 |              if False, each will be displayed separately.
 |
 |          vargs: Additional arguments that get passed into `plt.barh`.
 |              See http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.barh
 |              for additional arguments that can be passed into vargs.
 |
 |      Raises:
 |          ValueError -- Every selected except column for ``column_for_categories``
 |              must be numerical.
 |
 |      Returns:
 |          Horizontal bar graph with buckets specified by ``column_for_categories``.
 |          Each plot is labeled using the values in ``column_for_categories``
 |          and one plot is produced for every other column (or for the columns
 |          designated by ``select``).
 |
 |      >>> t = Table().with_columns(
 |      ...     'Furniture', make_array('chairs', 'tables', 'desks'),
 |      ...     'Count', make_array(6, 1, 2),
 |      ...     'Price', make_array(10, 20, 30)
 |      ...     )
 |      >>> t
 |      Furniture | Count | Price
 |      chairs    | 6     | 10
 |      tables    | 1     | 20
 |      desks     | 2     | 30
 |      >>> furniture_table.barh('Furniture') # doctest: +SKIP
 |      <bar graph with furniture as categories and bars for count and price>
 |      >>> furniture_table.barh('Furniture', 'Price') # doctest: +SKIP
 |      <bar graph with furniture as categories and bars for price>
 |      >>> furniture_table.barh('Furniture', make_array(1, 2)) # doctest: +SKIP
 |      <bar graph with furniture as categories and bars for count and price>
 |
 |  bin(self, *columns, **vargs)
 |      Group values by bin and compute counts per bin by column.
 |
 |      By default, bins are chosen to contain all values in all columns. The
 |      following named arguments from numpy.histogram can be applied to
 |      specialize bin widths:
 |
 |      If the original table has n columns, the resulting binned table has
 |      n+1 columns, where column 0 contains the lower bound of each bin.
 |
 |      Args:
 |          ``columns`` (str or int): Labels or indices of columns to be
 |              binned. If empty, all columns are binned.
 |
 |          ``bins`` (int or sequence of scalars): If bins is an int,
 |              it defines the number of equal-width bins in the given range
 |              (10, by default). If bins is a sequence, it defines the bin
 |              edges, including the rightmost edge, allowing for non-uniform
 |              bin widths.
 |
 |          ``range`` ((float, float)): The lower and upper range of
 |              the bins. If not provided, range contains all values in the
 |              table. Values outside the range are ignored.
 |
 |          ``density`` (bool): If False, the result will contain the number of
 |              samples in each bin. If True, the result is the value of the
 |              probability density function at the bin, normalized such that
 |              the integral over the range is 1. Note that the sum of the
 |              histogram values will not be equal to 1 unless bins of unity
 |              width are chosen; it is not a probability mass function.
 |
 |  boxplot(self, **vargs)
 |      Plots a boxplot for the table.
 |
 |      Every column must be numerical.
 |
 |      Kwargs:
 |          vargs: Additional arguments that get passed into `plt.boxplot`.
 |              See http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.boxplot
 |              for additional arguments that can be passed into vargs. These include
 |              `vert` and `showmeans`.
 |
 |      Returns:
 |          None
 |
 |      Raises:
 |          ValueError: The Table contains columns with non-numerical values.
 |
 |      >>> table = Table().with_columns(
 |      ...     'test1', make_array(92.5, 88, 72, 71, 99, 100, 95, 83, 94, 93),
 |      ...     'test2', make_array(89, 84, 74, 66, 92, 99, 88, 81, 95, 94))
 |      >>> table
 |      test1 | test2
 |      92.5  | 89
 |      88    | 84
 |      72    | 74
 |      71    | 66
 |      99    | 92
 |      100   | 99
 |      95    | 88
 |      83    | 81
 |      94    | 95
 |      93    | 94
 |      >>> table.boxplot() # doctest: +SKIP
 |      <boxplot of test1 and boxplot of test2 side-by-side on the same figure>
 |
 |  column(self, index_or_label)
 |      Return the values of a column as an array.
 |
 |      table.column(label) is equivalent to table[label].
 |
 |      >>> tiles = Table().with_columns(
 |      ...     'letter', make_array('c', 'd'),
 |      ...     'count',  make_array(2, 4),
 |      ... )
 |
 |      >>> list(tiles.column('letter'))
 |      ['c', 'd']
 |      >>> tiles.column(1)
 |      array([2, 4])
 |
 |      Args:
 |          label (int or str): The index or label of a column
 |
 |      Returns:
 |          An instance of ``numpy.array``.
 |
 |      Raises:
 |          ``ValueError``: When the ``index_or_label`` is not in the table.
 |
 |  column_index(self, label)
 |      Return the index of a column by looking up its label.
 |
 |  copy(self, *, shallow=False)
 |      Return a copy of a table.
 |
 |  drop(self, *column_or_columns)
 |      Return a Table with only columns other than selected label or
 |      labels.
 |
 |      Args:
 |          ``column_or_columns`` (string or list of strings): The header
 |          names or indices of the columns to be dropped.
 |
 |          ``column_or_columns`` must be an existing header name, or a
 |          valid column index.
 |
 |      Returns:
 |          An instance of ``Table`` with given columns removed.
 |
 |      >>> t = Table().with_columns(
 |      ...     'burgers',  make_array('cheeseburger', 'hamburger', 'veggie burger'),
 |      ...     'prices',   make_array(6, 5, 5),
 |      ...     'calories', make_array(743, 651, 582))
 |      >>> t
 |      burgers       | prices | calories
 |      cheeseburger  | 6      | 743
 |      hamburger     | 5      | 651
 |      veggie burger | 5      | 582
 |      >>> t.drop('prices')
 |      burgers       | calories
 |      cheeseburger  | 743
 |      hamburger     | 651
 |      veggie burger | 582
 |      >>> t.drop(['burgers', 'calories'])
 |      prices
 |      6
 |      5
 |      5
 |      >>> t.drop('burgers', 'calories')
 |      prices
 |      6
 |      5
 |      5
 |      >>> t.drop([0, 2])
 |      prices
 |      6
 |      5
 |      5
 |      >>> t.drop(0, 2)
 |      prices
 |      6
 |      5
 |      5
 |      >>> t.drop(1)
 |      burgers       | calories
 |      cheeseburger  | 743
 |      hamburger     | 651
 |      veggie burger | 582
 |
 |  exclude(self)
 |      Return a new Table without a sequence of rows excluded by number.
 |
 |      Args:
 |          ``row_indices_or_slice`` (integer or list of integers or slice):
 |              The row index, list of row indices or a slice of row indices
 |              to be excluded.
 |
 |      Returns:
 |          A new instance of ``Table``.
 |
 |      >>> t = Table().with_columns(
 |      ...     'letter grade', make_array('A+', 'A', 'A-', 'B+', 'B', 'B-'),
 |      ...     'gpa', make_array(4, 4, 3.7, 3.3, 3, 2.7))
 |      >>> t
 |      letter grade | gpa
 |      A+           | 4
 |      A            | 4
 |      A-           | 3.7
 |      B+           | 3.3
 |      B            | 3
 |      B-           | 2.7
 |      >>> t.exclude(4)
 |      letter grade | gpa
 |      A+           | 4
 |      A            | 4
 |      A-           | 3.7
 |      B+           | 3.3
 |      B-           | 2.7
 |      >>> t.exclude(-1)
 |      letter grade | gpa
 |      A+           | 4
 |      A            | 4
 |      A-           | 3.7
 |      B+           | 3.3
 |      B            | 3
 |      >>> t.exclude(make_array(1, 3, 4))
 |      letter grade | gpa
 |      A+           | 4
 |      A-           | 3.7
 |      B-           | 2.7
 |      >>> t.exclude(range(3))
 |      letter grade | gpa
 |      B+           | 3.3
 |      B            | 3
 |      B-           | 2.7
 |      >>> t.exclude(0, 2)
 |      letter grade | gpa
 |      A            | 4
 |      B+           | 3.3
 |      B            | 3
 |      B-           | 2.7
 |
 |      Note that ``exclude`` also supports NumPy-like indexing and slicing:
 |
 |      >>> t.exclude[:3]
 |      letter grade | gpa
 |      B+           | 3.3
 |      B            | 3
 |      B-           | 2.7
 |
 |      >>> t.exclude[1, 3, 4]
 |      letter grade | gpa
 |      A+           | 4
 |      A-           | 3.7
 |      B-           | 2.7
 |
 |  first(self, label)
 |      Return the zeroth item in a column.
 |
 |  group(self, column_or_label, collect=None)
 |      Group rows by unique values in a column; count or aggregate others.
 |
 |      Args:
 |          ``column_or_label``: values to group (column label or index, or array)
 |
 |          ``collect``: a function applied to values in other columns for each group
 |
 |      Returns:
 |          A Table with each row corresponding to a unique value in ``column_or_label``,
 |          where the first column contains the unique values from ``column_or_label``, and the
 |          second contains counts for each of the unique values. If ``collect`` is
 |          provided, a Table is returned with all original columns, each containing values
 |          calculated by first grouping rows according to ``column_or_label``, then applying
 |          ``collect`` to each set of grouped values in the other columns.
 |
 |      Note:
 |          The grouped column will appear first in the result table. If ``collect`` does not
 |          accept arguments with one of the column types, that column will be empty in the resulting
 |          table.
 |
 |      >>> marbles = Table().with_columns(
 |      ...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
 |      ...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
 |      ...    "Amount", make_array(4, 6, 12, 7, 9, 2),
 |      ...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00))
 |      >>> marbles
 |      Color | Shape       | Amount | Price
 |      Red   | Round       | 4      | 1.3
 |      Green | Rectangular | 6      | 1.3
 |      Blue  | Rectangular | 12     | 2
 |      Red   | Round       | 7      | 1.75
 |      Green | Rectangular | 9      | 1.4
 |      Green | Round       | 2      | 1
 |      >>> marbles.group("Color") # just gives counts
 |      Color | count
 |      Blue  | 1
 |      Green | 3
 |      Red   | 2
 |      >>> marbles.group("Color", max) # takes the max of each grouping, in each column
 |      Color | Shape max   | Amount max | Price max
 |      Blue  | Rectangular | 12         | 2
 |      Green | Round       | 9          | 1.4
 |      Red   | Round       | 7          | 1.75
 |      >>> marbles.group("Shape", sum) # sum doesn't make sense for strings
 |      Shape       | Color sum | Amount sum | Price sum
 |      Rectangular |           | 27         | 4.7
 |      Round       |           | 13         | 4.05
 |
 |  group_bar(self, column_label, **vargs)
 |      Plot a bar chart for the table.
 |
 |      The values of the specified column are grouped and counted, and one
 |      bar is produced for each group.
 |
 |      Note: This differs from ``bar`` in that there is no need to specify
 |      bar heights; the height of a category's bar is the number of copies
 |      of that category in the given column.  This method behaves more like
 |      ``hist`` in that regard, while ``bar`` behaves more like ``plot`` or
 |      ``scatter`` (which require the height of each point to be specified).
 |
 |      Args:
 |          ``column_label`` (str or int): The name or index of a column
 |
 |      Kwargs:
 |          overlay (bool): create a chart with one color per data column;
 |              if False, each will be displayed separately.
 |
 |          width (float): The width of the plot, in inches
 |          height (float): The height of the plot, in inches
 |
 |          vargs: Additional arguments that get passed into `plt.bar`.
 |              See http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.bar
 |              for additional arguments that can be passed into vargs.
 |
 |  group_barh(self, column_label, **vargs)
 |      Plot a horizontal bar chart for the table.
 |
 |      The values of the specified column are grouped and counted, and one
 |      bar is produced for each group.
 |
 |      Note: This differs from ``barh`` in that there is no need to specify
 |      bar heights; the size of a category's bar is the number of copies
 |      of that category in the given column.  This method behaves more like

In [11]:
!ls

Note1.ipynb

In [12]:
Table.read_table('./flowers.csv')

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

In [13]:
flowers = Table.read_table('flowers.csv')

In [14]:
flowers

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

In [16]:
f2 = pd.read_csv('./flowers.csv')

In [17]:
f2

   Petals       Name   Color
0       8      lotus    pink
1      34  sunflower  yellow
2       5       rose     red

In [22]:
f2['Name']

0        lotus
1    sunflower
2         rose
Name: Name, dtype: object

In [23]:
flowers.select('Name')

Name
lotus
sunflower
rose

In [24]:
f2.Name

0        lotus
1    sunflower
2         rose
Name: Name, dtype: object

In [25]:
f2[['Name']]

        Name
0      lotus
1  sunflower
2       rose